version: '3'

services:
  web:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - .:/app
      
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: